### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by PJPomPom** [yingkunwu/R-YOLOv4#6]
大佬救救我，该改哪呀，万分感谢！！！提前祝您春节快乐！！！

Traceback (most recent call last):
  File "/home/zero/pjpompom/R-YOLOv4-main(test)/test.py", line 65, in <module>
    sample_metrics += get_batch_statistics(outputs, targets, iou_threshold=args.iou_thres)
  File "/home/zero/pjpompom/R-YOLOv4-main(test)/tools/utils.py", line 191, in get_batch_statistics
    if pred_label not in target_labels:
  File "/home/zero/anaconda3/envs/pjpompom/lib/python3.8/site-packages/torch/tensor.py", line 646, in __contains__
    return (element == self).any().item()  # type: ignore[union-attr]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by yingkunwu** [comment]
Hi, 這個我修好了，再幫我重新pull一下試試，感謝！

**Comment by PJPomPom** [comment]
不好意思，大佬，我不太会操作，希望大佬有机会可以来bilibili弹幕网，那里很多学习爱好者。
